# ========== Makefile ==========
# Builds leak_test_exec from:
#   - main.c  (generated by run.sh)
#   - src/leak_tracker.c
#
# Usage:  make
# run.sh will create main.c for you before invoking make.

CC      := gcc
CFLAGS  := -g -Wall -Isrc
TARGET  := leak_test_exec

SRCS    := main.c src/leak_tracker.c
OBJS    := $(SRCS:.c=.o)

.PHONY: all clean

all: $(TARGET)

# Compile any .c into .o (main.c or src/leak_tracker.c),
# provided leak_tracker.h is present for dependencies.
%.o: %.c src/leak_tracker.h
	$(CC) $(CFLAGS) -c $< -o $@

# Link step: link all object files into the final executable
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

clean:
	rm -f $(OBJS) $(TARGET) main.c
